# Generated by Django 5.2 on 2025-05-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0002_alter_dog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
